apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app-deployment
  labels:
    app: blog-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      imagePullSecrets:
      - name: ibm-cloud-secret
      containers:
      - name: blog-app
        image: icr.io/cloud-namespace12345/blogapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # Changed from 3000 to 8080
        env:
        - name: MY_APP_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080  # Changed from 3000 to 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080  # Changed from 3000 to 8080
          initialDelaySeconds: 10
          periodSeconds: 5


---

apiVersion: v1
kind: Service
metadata:
  name: pyhton-web-app-service
spec:
  type: NodePort
  selector:
    app: blog-app
  ports:
  - port: 80
    targetPort: 8080  # Changed from 3000 to 8080
    nodePort: 30001
